perf: update version shell

diff --git a/gcp-shell/gcp-cloud-proxy b/gcp-shell/gcp-cloud-proxy
--- a/gcp-shell/gcp-cloud-proxy
+++ b/gcp-shell/gcp-cloud-proxy
@@ -1,115 +1,152 @@
-#!/bin/sh
+#!/usr/bin/env bash
 # Auhtor: Ted Vo - 2022/11/08
 # Shell hellper connect sql cloud via proxy
 
+# https://gist.github.com/vncsna/64825d5609c146e80de8b1fd623011ca
+set -euo pipefail
+
+SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
 OS_ARCH=$(uname | tr '[:upper:]' '[:lower:]')
 BIN_PATH=/usr/local/bin
 CLOUD_SQL_PROXY=$BIN_PATH/cloud_sql_proxy
+ICON_PASSED='\e[1;32m√\e[0m'
+ICON_ERROR='\e[1;31mx\e[0m'
 
 global_help() {
-  echo ""
-  echo "Shell script for run SQL Auth proxy client" 
-  echo ""
-  echo "Usage:"
-  echo "gcp-cloud-proxy [flag] => flag for fast connect mode"
-  echo "gcp-cloud-proxy        => without flag for selection mode"
-  echo " "
-  echo "Available Commands:"
-  echo ""
-  echo "Flags:"
-  echo "  -h, --help                show brief help"
-  echo "  -c, --connection-name     projectID:region:instanceID"
-  echo "  -p, --port                port local for forwarding"
-  exit 0
+	echo ""
+	echo "Shell script for run SQL Auth proxy client"
+	echo ""
+	echo "Usage:"
+	echo "gcp-cloud-proxy [flag] => flag for fast connect mode"
+	echo "gcp-cloud-proxy        => without flag for selection mode"
+	echo " "
+	echo "Available Commands:"
+	echo ""
+	echo "Flags:"
+	echo "  -h, --help                show brief help"
+	echo "  -c, --connection-name     projectID:region:instanceID"
+	echo "  -p, --port                port local for forwarding"
+	exit 0
 }
 
-install_cloud_sql_proxy_client() {
-  echo ""
-  echo " Downloading Cloud SQL Auth proxy client..."
-  if [ $OS_ARCH == "darwin" ]; then
-    curl -o $CLOUD_SQL_PROXY https://dl.google.com/cloudsql/cloud_sql_proxy.darwin.amd64
-  elif [ $OS_ARCH == "linux" ]; then
-    wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O $CLOUD_SQL_PROXY
-  fi
-
-  echo " Grant execute permission"
-  chmod +x $CLOUD_SQL_PROXY
-
-  echo " Done"
-  echo ""
+pass() {
+	printf '%s %s' "$ICON_PASSED" "$1"
 }
 
-require_shell() {
-  if ! cloud_sql_proxy -version &> /dev/null; then
-  echo "\"cloud_sql_proxy\" cloud not be found."
-  while true; do
-    read -p "Do you wish to install this program? (Yy or Nn): " yn
-    case $yn in
-      [Yy]* ) install_cloud_sql_proxy_client; break;;
-      [Nn]* ) exit;;
-      * ) echo "Please answer yes or no.";;
-    esac
-  done
- fi
+failure() {
+	printf '%s %s' "$ICON_ERROR" "$1"
+}
+
+install() {
+	echo "Cloud SQL Proxy"
+	echo "---------------"
+	if cloud_sql_proxy -version &>/dev/null; then
+		pass "installed\n"
+	else
+		echo "Downloading Cloud SQL Auth proxy client..."
+		if [[ $OS_ARCH == "darwin" ]]; then
+			curl -o $CLOUD_SQL_PROXY https://dl.google.com/cloudsql/cloud_sql_proxy.darwin.amd64
+		elif [[ $OS_ARCH == "linux" ]]; then
+			wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O $CLOUD_SQL_PROXY
+		fi
+
+		echo " Grant execute permission"
+		chmod +x $CLOUD_SQL_PROXY
+
+		pass "DONE\n"
+	fi
+
+	echo ""
+	echo ""
+	echo "Cloud SQL Proxy Hepler"
+	echo "----------------------"
+	if which gcp-cloud-proxy &>/dev/null; then
+		pass "installed\n"
+	else
+		ln -sf "$SCRIPT_DIR"/gcp-cloud-proxy.sh /usr/local/bin/gcp-cloud-proxy
+		/usr/local/bin/gcp-cloud-proxy -h
+		pass "DONE\n"
+	fi
 }
 
 connect_database() {
-  require_shell
-
-  # check port or assign default: 3306
-  if [ -z "$PORT" ]; then
-    PORT=3306
-  fi
-  echo ""
-  echo "-----------------------------------------------------------"
-  echo " Running with `cloud_sql_proxy -version`"
-  echo " Host: localhost"
-  echo " Port: $PORT"
-  echo "-----------------------------------------------------------"
-  cloud_sql_proxy -instances=$1=tcp:$PORT "-ip_address_types=PRIVATE"
+	# check port or assign default: 3306
+	if [[ -z $PORT ]]; then
+		PORT=3306
+	fi
+	echo ""
+	echo "-----------------------------------------------------------"
+	echo " Running with $(cloud_sql_proxy -version)"
+	echo " Host: localhost"
+	echo " Port: $PORT"
+	echo "-----------------------------------------------------------"
+	cloud_sql_proxy -instances="$1"=tcp:"$PORT" "-ip_address_types=PRIVATE"
 }
 
 selection_mode() {
-  PROJECT_ID=$(gcloud config get-value project)
-  REGION=$(gcloud config get-value compute/region)
-  echo ""
-  echo "-----------------------------------------------------------"
-  echo " Current GCP Project-Id: $PROJECT_ID"
-  echo "             Region    : $REGION"
-  echo "-----------------------------------------------------------"
-  echo " List SQL Instances"
-  gcloud sql instances list
-  echo "-----------------------------------------------------------"
+	PROJECT_ID=$(gcloud config get-value project)
+	REGION=$(gcloud config get-value compute/region)
 
-  read -p "Enter instance name ($PROJECT_ID:$REGION:YOUR_INPUT): " INSTANCE_NAME
-  connect_database $PROJECT_ID:$REGION:$INSTANCE_NAME
+	if [[ -z $PROJECT_ID ]]; then
+		echo "Error: Project not config"
+		exit 1
+	fi
+
+	if [[ -z $REGION ]]; then
+		failure "Region not config\n"
+	fi
+
+	echo ""
+	echo "-----------------------------------------------------------"
+	echo " Current GCP Project-Id: $PROJECT_ID"
+	echo "-----------------------------------------------------------"
+	echo " List SQL Instances"
+	gcloud sql instances list
+	echo "-----------------------------------------------------------"
+
+	if [[ -z $REGION ]]; then
+		read -rp "Enter REGION (location without zone a/b/c): " REGION
+	fi
+
+	read -rp "Enter NAME ($PROJECT_ID:$REGION:YOUR_INPUT) : " INSTANCE_NAME
+	connect_database "$PROJECT_ID":"$REGION":"$INSTANCE_NAME"
 }
 
+PORT=""
+CONNECTION_NAME=""
 while test $# -gt 0; do
-  case "$1" in
-    -h|--help)
-      global_help ;;
-    -c|--connection-name)
-      shift
-      CONNECTION_NAME=$1
-      shift
-      ;;
-    -p|--port)
-      shift
-      PORT=$1
-      shift
-      ;;
-    *)
-      echo ""
-      echo "Run 'gcp-cloud-proxy -h|--help' for usage."
-      exit 1
-      break
-      ;;
-  esac
+	case "$1" in
+	-h | --help)
+		global_help
+		;;
+	-c | --connection-name)
+		shift
+		CONNECTION_NAME=$1
+		shift
+		;;
+	-p | --port)
+		shift
+		PORT=$1
+		shift
+		;;
+	install)
+		"$@"
+		exit
+		;;
+	*)
+		echo ""
+		echo "Run 'gcp-cloud-proxy -h|--help' for usage."
+		exit 1
+		;;
+	esac
 done
 
-if [ ! -z $CONNECTION_NAME ]; then
-  connect_database $CONNECTION_NAME
-else
-  selection_mode
-fi
+main() {
+	if [ -z "$CONNECTION_NAME" ]; then
+		selection_mode
+	else
+		connect_database "$CONNECTION_NAME"
+	fi
+}
+
+main
diff --git a/protobuf-tools/protubuf-helper b/protobuf-tools/protubuf-helper
--- a/protobuf-tools/protubuf-helper
+++ b/protobuf-tools/protubuf-helper
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # author: ted-vo - 2022/11/30
 # Shell helper for developer
 
@@ -6,10 +6,10 @@
 # set -e, -u, -o, -x pipefail
 set -euo pipefail
 
-SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+# SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
-if [ $OS == "darwin" ]; then
-  OS="osx"
+if [ "$OS" == "darwin" ]; then
+	OS="osx"
 fi
 ARCH="$(uname -m | tr '[:upper:]' '[:lower:]')"
 
@@ -18,197 +18,197 @@ PLUGIN_GEN_GRPC_JAVA_VERSION=1.47.0
 PLUGIN_GEN_GRPC_WEB_VERSION=1.4.2
 
 header() {
-  echo ""
-  echo "--------------------------------------------------------------------"
-  echo " ⚙️  $1 "
-  echo "--------------------------------------------------------------------"
+	echo ""
+	echo "--------------------------------------------------------------------"
+	echo " ⚙️  $1 "
+	echo "--------------------------------------------------------------------"
 }
 
 footer() {
-  echo " ✅ OK"
+	echo " ✅ OK"
 }
 
 spin() {
-  local i=0
-  local sp='/-\|'
-  local n=${#sp}
-  sleep 0.1
-  while true; do
-    printf "\b%s" "${sp:i++%n:1}"
-    sleep 0.2
-  done
+	local i=0
+	local sp='/-\|'
+	local n=${#sp}
+	sleep 0.1
+	while true; do
+		printf "\b%s" "${sp:i++%n:1}"
+		sleep 0.2
+	done
 }
 
 show_loading() {
-  spin &
-  SPIN_PID=$!
-  # Kill the spinner on any signal, including our own exit.
-  trap "kill -9 $SPIN_PID &> /dev/null" `seq 0 15`
+	spin &
+	SPIN_PID=$!
+	# Kill the spinner on any signal, including our own exit.
+	trap 'kill -9 $SPIN_PID &> /dev/null' $(seq 0 15)
 }
 
 hide_loading() {
-  printf "\bDone \e[1;32m√\e[0m\n"
-  kill -9 $SPIN_PID &> /dev/null
+	printf "\bDone \e[1;32m√\e[0m\n"
+	kill -9 $SPIN_PID &>/dev/null
 }
 
 check_go_bin() {
-  header "checking go"
+	header "checking go"
 
-  if ! which go &> /dev/null; then
-    echo " ❌ Please install golang first inorder to install go protoc generator"
-    exit 1
-  fi
+	if ! which go &>/dev/null; then
+		echo " ❌ Please install golang first inorder to install go protoc generator"
+		exit 1
+	fi
 
-  footer
+	footer
 }
 
 check_protoc() {
-  header "checking protoc"
+	header "checking protoc"
 
-  if ! which protoc &> /dev/null; then
-    printf " ❌ protoc not found. Installing... "
-    show_loading
+	if ! which protoc &>/dev/null; then
+		printf " ❌ protoc not found. Installing... "
+		show_loading
 
-    PB_REL="https://github.com/protocolbuffers/protobuf/releases"
-    PROTOC_ZIP_NAME="protoc-${PROTOC_VERSION}-${OS}-${ARCH}.zip"
+		PB_REL="https://github.com/protocolbuffers/protobuf/releases"
+		PROTOC_ZIP_NAME="protoc-${PROTOC_VERSION}-${OS}-${ARCH}.zip"
 
-    curl -LOs $PB_REL/download/v${PROTOC_VERSION}/$PROTOC_ZIP_NAME
-    unzip -qo $PROTOC_ZIP_NAME bin/protoc -d /usr/local
-    rm $PROTOC_ZIP_NAME
+		curl -LOs $PB_REL/download/v${PROTOC_VERSION}/"$PROTOC_ZIP_NAME"
+		unzip -qo "$PROTOC_ZIP_NAME" bin/protoc -d /usr/local
+		rm "$PROTOC_ZIP_NAME"
 
-    hide_loading
-  fi
+		hide_loading
+	fi
 
-  footer
+	footer
 }
 
 check_protoc_gen_validate() {
-  header "checking protoc-gen-validate"
+	header "checking protoc-gen-validate"
 
-  if ! which protoc-gen-validate &> /dev/null; then
-    printf " ❓ protoc-gen-validate not found. Installing... "
-    show_loading
-    go install github.com/envoyproxy/protoc-gen-validate@latest
-    hide_loading
-  fi
- 
-  footer
+	if ! which protoc-gen-validate &>/dev/null; then
+		printf " ❓ protoc-gen-validate not found. Installing... "
+		show_loading
+		go install github.com/envoyproxy/protoc-gen-validate@latest
+		hide_loading
+	fi
+
+	footer
 }
 
 check_protoc_gen_go() {
-  header "checking protoc-gen-go"
-  
-  if ! which protoc-gen-go &> /dev/null ; then
-    printf " ❓ protoc-gen-go not found. Installing... "
-    show_loading
-    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
-    hide_loading
-  fi
+	header "checking protoc-gen-go"
 
-    footer
+	if ! which protoc-gen-go &>/dev/null; then
+		printf " ❓ protoc-gen-go not found. Installing... "
+		show_loading
+		go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
+		hide_loading
+	fi
+
+	footer
 }
 
 check_protoc_gen_go_grpc() {
-  header "checking protoc-gen-go-grpc"
+	header "checking protoc-gen-go-grpc"
 
-  if ! which protoc-gen-go-grpc &> /dev/null; then
-    printf " ❓ protoc-gen-go-grpc not found. Installing... "
-    show_loading
-    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
-    hide_loading
-  fi
+	if ! which protoc-gen-go-grpc &>/dev/null; then
+		printf " ❓ protoc-gen-go-grpc not found. Installing... "
+		show_loading
+		go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
+		hide_loading
+	fi
 
-  footer
+	footer
 }
 
 check_protoc_gen_grpc_gateway() {
-  header "check protoc-gen-grpc-gateway"
+	header "check protoc-gen-grpc-gateway"
 
-  if ! which protoc-gen-grpc-gateway &> /dev/null ; then
-    printf " ❓ protoc-gen-grpc-gateway not found. Installing... "
-    show_loading
-    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
-    hide_loading
-  fi
+	if ! which protoc-gen-grpc-gateway &>/dev/null; then
+		printf " ❓ protoc-gen-grpc-gateway not found. Installing... "
+		show_loading
+		go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
+		hide_loading
+	fi
 
-  footer
+	footer
 }
 
 check_protoc_gen_swagger() {
-  header "checking protoc-gen-swagger"
-  
-  if ! which protoc-gen-swagger &> /dev/null; then
-    printf " ❓ protoc-gen-swagger not found. Installing... "
-    show_loading
-    go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger@latest
-    hide_loading
-  fi
+	header "checking protoc-gen-swagger"
 
-  footer
+	if ! which protoc-gen-swagger &>/dev/null; then
+		printf " ❓ protoc-gen-swagger not found. Installing... "
+		show_loading
+		go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger@latest
+		hide_loading
+	fi
+
+	footer
 }
 
 check_protoc_gen_grpc_java() {
-  header "checking protoc-gen-grpc-java"
+	header "checking protoc-gen-grpc-java"
 
-  if ! which protoc-gen-grpc-java &> /dev/null; then
-    printf " ❓ protoc-gen-grpc-java not found. Installing... "
-    show_loading
-    
-    PB_REL="https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java"
-    GRPC_JAVA="protoc-gen-grpc-java-${PLUGIN_GEN_GRPC_JAVA_VERSION}-${OS}-${ARCH}.exe"
-    PLUGIN_NAME=protoc-gen-grpc-java
-    curl -LOs $PB_REL/${PLUGIN_GEN_GRPC_JAVA_VERSION}/$GRPC_JAVA \
-      && mv $GRPC_JAVA /usr/local/bin/$PLUGIN_NAME \
-      && chmod +x /usr/local/bin/$PLUGIN_NAME
+	if ! which protoc-gen-grpc-java &>/dev/null; then
+		printf " ❓ protoc-gen-grpc-java not found. Installing... "
+		show_loading
 
-    hide_loading
-  fi
+		PB_REL="https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java"
+		GRPC_JAVA="protoc-gen-grpc-java-${PLUGIN_GEN_GRPC_JAVA_VERSION}-${OS}-${ARCH}.exe"
+		PLUGIN_NAME=protoc-gen-grpc-java
+		curl -LOs $PB_REL/${PLUGIN_GEN_GRPC_JAVA_VERSION}/"$GRPC_JAVA" &&
+			mv "$GRPC_JAVA" /usr/local/bin/$PLUGIN_NAME &&
+			chmod +x /usr/local/bin/$PLUGIN_NAME
 
-  footer
+		hide_loading
+	fi
+
+	footer
 }
 
 check_protoc_gen_grpc_web() {
-  header "checking protoc-gen-grpc-web"
-  
-  if ! which protoc-gen-grpc-web &> /dev/null; then
-    printf " ❓ protoc-gen-grpc-web not found. Installing... "
-    show_loading
+	header "checking protoc-gen-grpc-web"
 
-    PB_REL="https://github.com/grpc/grpc-web/releases"
-    GRPC_WEB="protoc-gen-grpc-web-${PLUGIN_GEN_GRPC_WEB_VERSION}-$(uname -s | tr '[:upper:]' '[:lower:]')-${ARCH}"
-    PLUGIN_NAME=protoc-gen-grpc-web
-    curl -LOs $PB_REL/download/${PLUGIN_GEN_GRPC_WEB_VERSION}/${GRPC_WEB} \
-      && mv $GRPC_WEB /usr/local/bin/$PLUGIN_NAME \
-      && chmod +x /usr/local/bin/$PLUGIN_NAME
+	if ! which protoc-gen-grpc-web &>/dev/null; then
+		printf " ❓ protoc-gen-grpc-web not found. Installing... "
+		show_loading
 
-    hide_loading
-  fi
+		PB_REL="https://github.com/grpc/grpc-web/releases"
+		GRPC_WEB="protoc-gen-grpc-web-${PLUGIN_GEN_GRPC_WEB_VERSION}-$(uname -s | tr '[:upper:]' '[:lower:]')-${ARCH}"
+		PLUGIN_NAME=protoc-gen-grpc-web
+		curl -LOs $PB_REL/download/${PLUGIN_GEN_GRPC_WEB_VERSION}/"${GRPC_WEB}" &&
+			mv "$GRPC_WEB" /usr/local/bin/$PLUGIN_NAME &&
+			chmod +x /usr/local/bin/$PLUGIN_NAME
 
-  footer
+		hide_loading
+	fi
+
+	footer
 }
 
 main() {
-  check_go_bin
+	check_go_bin
 
-  # protobuf
-  check_protoc
+	# protobuf
+	check_protoc
 
-  # validate
-  check_protoc_gen_validate
+	# validate
+	check_protoc_gen_validate
 
-  # grpc-gateway
-  check_protoc_gen_grpc_gateway
-  check_protoc_gen_swagger
+	# grpc-gateway
+	check_protoc_gen_grpc_gateway
+	check_protoc_gen_swagger
 
-  # go
-  check_protoc_gen_go
-  check_protoc_gen_go_grpc
+	# go
+	check_protoc_gen_go
+	check_protoc_gen_go_grpc
 
-  # grpc-java
-  check_protoc_gen_grpc_java
+	# grpc-java
+	check_protoc_gen_grpc_java
 
-  # grpc-web
-  check_protoc_gen_grpc_web
+	# grpc-web
+	check_protoc_gen_grpc_web
 }
 
 main
